check50:
  checks: checks.py
  files: &check50_files
    - !exclude "*"
    - !require climate.ipynb
  dependencies:
    - "jupyter"
    - "git+https://github.com/jelleas/uva_check50.git#egg=uva.check50>=0.0.3"
    - "matplotlib"
    - "seaborn"
